### ISSUE TITLE
JobPiplelines as batched jobs

### ISSUE THREAD

**Issue by morloderex** [archtechx/jobpipeline#5]
**Description**
Add ability to dispatch the pipeline as a batched job.

**Why it should be implemented**
Currently when some event in the pipeline fails the entire pipeline is considered failed. This seems like the correct behavior. 

However, as one might notice if you retry the pipeline again the entire pipeline is being executed once more, not from the the point of the failure leading to unexpected additional failures.

This also has the benefit of allowing for catching pipeline failures or successes.

**Comment by stancl** [comment]
Hey,

That's an interesting suggestion. Would make it possible to retry the jobs. But at the same time, I can imagine that retrying specific jobs could be impossible, because the first half of a job can still execute, make changes, and the second half can fail.

Still, this would be a nice feature. Those edge cases are up to the user to take care of. Feel free to send a PR!

**Comment by morloderex** [comment]
@stancl This does not seem to be that simple to implement.

Here is the "perfect world" proposed api
```php 
JobPipeline::make([
    FirstJob::class,
    SecondJob::class,
])->send(function (TestEvent $event) {
    return [$event->testModel, $this->valuestore];
})->asBatch() // would return a PendingBatch class for configuring the batch
   ->then()
   ->name()
   ->finally()
   ->catch()
   ->allowFailures()
   ->dispatch()
```
But due to the nature of events and how the internals of JobPipelines currently works with closures this seems atleast to me to be impossible, sense the current `toListener` is returning a closure and reassigning the pipeline internally. 

Do you have any other suggestions for a possible api because passing in arguments to the `asBatch` method to me seems kinda tidious.
